# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Los Cachivaches de Cantor"
email: dgda1991@gmail.com
description: "Todo morfismo Curiosidad → Belleza, en la categoría de redes sociales es un isomorfismo local. (Lema: La demostración se deja como ejercicio al lector.)"
baseurl: "/Los-Cachivaches-de-Cantor"
url: "https://danito3d.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
social_links:
  - name: "Facebook"
    icon: "facebook"  # Ícono estándar de Minima
    url: "https://www.facebook.com/profile.php?id=61575577703063&locale=es_LA"
favicon:  C:\Users\pcnue\Los-Cachivaches-de-Cantor\assets\images
sass:
  sass_dir: assets/css
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
